create table if not exists hardware_live_status (
  computer_name text primary key,
  user_name text,
  cpu_percent numeric default 0,
  memory_percent numeric default 0,
  memory_used_gb numeric default 0,
  memory_total_gb numeric default 0,
  disk_percent numeric default 0,
  disk_free_percent numeric,
  uptime_seconds bigint,
  active_process text,
  activity_category text,
  top_cpu jsonb default '[]'::jsonb,
  top_memory jsonb default '[]'::jsonb,
  top_io jsonb default '[]'::jsonb,
  agent_version text,
  last_seen timestamptz default now(),
  created_at timestamptz default now()
);

create table if not exists hardware_performance_history (
  id bigint generated by default as identity primary key,
  computer_name text not null,
  sampled_at timestamptz default now(),
  cpu_percent numeric default 0,
  memory_percent numeric default 0,
  disk_percent numeric default 0,
  active_process text,
  activity_category text,
  top_processes jsonb default '{}'::jsonb
);

create table if not exists hardware_performance_alerts (
  id uuid primary key default gen_random_uuid(),
  computer_name text not null,
  metric text not null,
  peak_value numeric not null,
  threshold numeric default 98,
  status text default 'Ativo',
  started_at timestamptz default now(),
  recovered_at timestamptz,
  duration_seconds int,
  cause_process text,
  activity_category text,
  top_processes jsonb default '{}'::jsonb,
  message text,
  created_at timestamptz default now()
);

create index if not exists idx_hw_history_computer_time
on hardware_performance_history (computer_name, sampled_at desc);

create index if not exists idx_hw_alerts_computer_time
on hardware_performance_alerts (computer_name, started_at desc);

create or replace function cleanup_old_hardware_performance_history()
returns trigger language plpgsql as $$
begin
  delete from hardware_performance_history
  where computer_name = new.computer_name
    and sampled_at < now() - interval '90 days';
  return new;
end $$;

drop trigger if exists cleanup_hardware_performance_history on hardware_performance_history;
create trigger cleanup_hardware_performance_history
after insert on hardware_performance_history
for each row execute function cleanup_old_hardware_performance_history();

alter table hardware_live_status enable row level security;
alter table hardware_performance_history enable row level security;
alter table hardware_performance_alerts enable row level security;

drop policy if exists "Telemetria leitura" on hardware_live_status;
create policy "Telemetria leitura" on hardware_live_status for select to anon using (true);
drop policy if exists "Telemetria envio" on hardware_live_status;
create policy "Telemetria envio" on hardware_live_status for insert to anon with check (true);
drop policy if exists "Telemetria atualizacao" on hardware_live_status;
create policy "Telemetria atualizacao" on hardware_live_status for update to anon using (true) with check (true);

drop policy if exists "Historico leitura" on hardware_performance_history;
create policy "Historico leitura" on hardware_performance_history for select to anon using (true);
drop policy if exists "Historico envio" on hardware_performance_history;
create policy "Historico envio" on hardware_performance_history for insert to anon with check (true);

drop policy if exists "Alertas leitura" on hardware_performance_alerts;
create policy "Alertas leitura" on hardware_performance_alerts for select to anon using (true);
drop policy if exists "Alertas envio" on hardware_performance_alerts;
create policy "Alertas envio" on hardware_performance_alerts for insert to anon with check (true);
drop policy if exists "Alertas atualizacao" on hardware_performance_alerts;
create policy "Alertas atualizacao" on hardware_performance_alerts for update to anon using (true) with check (true);

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='hardware_live_status') then
    alter publication supabase_realtime add table hardware_live_status;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='hardware_performance_alerts') then
    alter publication supabase_realtime add table hardware_performance_alerts;
  end if;
end $$;
